package com.alipay.global.api.model.aps;

public enum AttachmentType {
    ARTICLES_OF_ASSOCIATION,
    ENTERPRISES_ANNUAL_INSPECTION_REPORT,
    PROOF_OF_ADDRESS,
    OTHER_MATERIAL,
    REGISTRATION_CERTIFICATE,
    TRANSACTION_RECEIPT,
    PROOF_OF_DELIVERY,
    MERCHANT_INFORMATION,
    END_USER_INFORMATION,
    OTHER_DOCUMENTATION,
    MERCHANT_NOT_REFUND_RECORDS,
    SUPPORTING_DOCUMENTATION
}
